# Generated by Django 5.2.8 on 2025-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('casual', 'Casual'), ('simulation', 'Simulation'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('rpg', 'RPG'), ('racing', 'Racing'), ('software', 'Software'), ('shooter', 'Shooter'), ('survival', 'Survival'), ('multiplayer', 'Multiplayer')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('icon', models.ImageField(upload_to='game_icons/')),
                ('genre', models.ManyToManyField(blank=True, related_name='games', to='firstApp.genres')),
            ],
        ),
    ]
